### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.form#13]
This is the diff of the versions between the last version which ran successfully and the first one which is broken:

```diff
 beautifulsoup4==4.12.3
-BTrees==6.0
+BTrees==6.1
 cffi==1.17.1
-multipart==0.2.5
-persistent==6.0
+multipart==1.0.0
+persistent==6.1
 pip==24.2
 pycparser==2.22
 python-gettext==5.0
 pytz==2024.2
-setuptools==74.1.2
+setuptools==75.1.0
 soupsieve==2.6
-transaction==4.0
+transaction==5.0
 waitress==3.0.0
 WebOb==1.8.8
 WebTest==3.0.1
@@ -19,10 +19,10 @@
 ZConfig==4.1
 zdaemon==5.1
 ZODB==6.0
-zodbpickle==4.0
+zodbpickle==4.1
 zope.annotation==5.0
 zope.app.wsgi==5.0
 zope.authentication==5.0
@@ -33,7 +33,7 @@
 zope.cachedescriptors==5.0
 zope.component==6.0
 zope.configuration==5.0.1
-zope.container==6.0
+zope.container==6.1
 zope.contenttype==5.1
 zope.datetime==5.0.0
 zope.deferredimport==5.0
@@ -45,9 +45,9 @@
 zope.exceptions==5.1
 zope.filerepresentation==6.0
 zope.formlib==6.0
-zope.hookable==6.0
+zope.hookable==7.0
 zope.i18n==5.1
-zope.i18nmessageid==6.1.0
+zope.i18nmessageid==7.0
 zope.interface==7.0.3
 zope.intid==5.0
 zope.keyreference==6.0
```

I think it is the update of `multipart` which broke our tests.
Example: https://github.com/zopefoundation/zope.app.form/actions/runs/11322471235/job/31483223429

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-10-16 09:32 -0700:
>This is the diff of the versions between the last version which ran successfully and the first one which is broken:
> ...
>I think it is the update of `multipart` which broke our tests.

I have seen hints elsewhere (I think `zope.publisher`)
that `multipart 1.x` has introduced incompatible changes that may
require adaptations in `ZPublisher`.

**Comment by mgedmin** [comment]
multipart 1.0.0 requires the HTTP stream to use actual `\r\n` line endings, which has tripped a test suite in zope.publisher.  The fix was simple there: https://github.com/zopefoundation/zope.publisher/commit/a44be991767c3d0a93db589b9ce932918de0d3b6

**Comment by icemac** [comment]
@mgedmin Thank you for this tip. I am using it in #14 to fix the tests.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-10-16 09:32 -0700:
> ...
>I think it is the update of `multipart` which broke our tests.

You are right!
`multipart 1.x` now insists on `\r\n` line separators
(formerly, it accepted `\n`, too).

This may bite us at other places, too.
